### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [lesterchan/gamerz-file-explorer#2]
Hi @lesterchan ,, I am a graphic designer. I wanted to contribute to your project and I've designed a logo for your project. If you like it, I'll send you files and pr. what do you think?
![search](https://user-images.githubusercontent.com/36124339/46662319-4a578880-cbe5-11e8-8c65-b8e47caf1617.png)

**Comment by lesterchan** [comment]
Wow, looks good! Sure thing! I like the light orange one!

**Comment by mirzazulfan** [comment]
Thanks for your response @lesterchan, im glad you liked it. I'll send you files and pr. What is the name of your project? Best regard.

**Comment by lesterchan** [comment]
`GaMerZ File Explorer` =)

**Comment by mirzazulfan** [comment]
Hi @lesterchan .. I've created a pr #3. You can download all files in [GDrive](https://drive.google.com/drive/folders/1DNpaZaZ_JMtVMGDJodSKUhy_ifhu0ji_?ogsrc=32). If you need anything change in the future, dont hesitate to contact me. Email : mirzazulfan@gmail.com

Best Regard. Mirza Zulfan

**Comment by lesterchan** [comment]
Thanks =) Merged to a new branch. I will probably clean it up like file name, SVG code. And with SVG, I just need 1 image.

**Comment by mirzazulfan** [comment]
Glad to hear that. Good luck with your project. :100:

**Comment by lesterchan** [comment]
Thanks https://github.com/lesterchan/gamerz-file-explorer/commit/f0a0fadc967e8b1842d35f412fe46dfde0392376 =)
